### ISSUE TITLE
Executing parasol_main

### ISSUE THREAD

**Issue by Sinsha30** [sonofeft/ParaSol#1]
Hi there! I'm encountering a high number of errors while trying to execute the "Parasol example" of the Rocket CEA documentation. To solve this, I was trying to adjust the "parasol_main" code but it keeps bringing more and more errors and what I'm doing doesn't feel right anymore. As I have not seen anyone reporting such an isssue, I'm wondering of it's just coming from my install. I installed it both with pip and from GitHub. Or is there an updated version of ParaSol which I missed ? I'm working on Windows 11 with Python 3.9.
Many thanks if you can help :)

**Comment by sonofeft** [comment]
I'm sorry I have not updated Parasol for a number of years. It is still a python 2.X application. Give me a little time to convert it to python 3.X. I will drop support for 2.X in the next version.

**Comment by sonofeft** [comment]
I made a version 0.2.1 that should work with python 3.x. I'm sorry the test coverage is pretty poor, however, it does run the test cases under python 3.7 and 3.10. There is still work to be done, however, this should get you going.

You can install it with: 
pip install parasol
OR
pip install --upgrade parasol

Let me know if you have trouble.

**Comment by Sinsha30** [comment]
It's working! Thanks a lot for fixing it so fast!
